### ISSUE TITLE
Web serber is no longer available

### ISSUE THREAD

**Issue by FredericFlayol** [rsmp-nordic/rsmp_documentation#7]
Hello,
all links about RSMP returns a 404 error:
For instance:
https://rsmp-nordic.org/rsmp_specifications/core/3.2/applicability/basic_structure.html#alarm-messages
![image](https://github.com/rsmp-nordic/rsmp_specifications/assets/135714972/ccd69cd5-97bd-45dc-9c08-a3f35f7500d0)
Same for all links in https://github.com/rsmp-nordic/rsmp_specifications

Best regards,

**Comment by otterdahl** [comment]
We'll look into it. Until fixed, they are still available here: https://rsmp-nordic.github.io/rsmp_specifications/core/3.2/

**Comment by FredericFlayol** [comment]
Thank you for your help.

**Comment by otterdahl** [comment]
The links should be working again. Thanks for reporting this
